server:
  port: 8000

spring:
  application:
    name: my-zuul-serice

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://localhost:8001
    second-service:
      path: /second-service/**
      url: http://localhost:8002
